<!DOCTYPE HTML>
<html>
<?php
// Get the variables we need from above page, which isn't many because this is mainly static.
$username = $_COOKIE['username'];
if(empty($username)) {
$username = "Aidan";
}
?>
<?php /* [Begin MIST Header Include] (c) 2012 Leading Potential, All Rights Reserved. (c) 2012 Beaconsfield IT, All Rights Reserved. */ ?>
<!-- This HTML is generated by the Mist engine - Content is copyright by it's respective owners.
  -- Mist is (c) 2010 - 2012 Beaconsfield IT, All Rights Reserved.
  -- All content hereinafter is (c) 2010 - 2012 Leading Potential / Generative Leadership.
  -- Illigal reproduction will be punished to the full extent of the law. 
  -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=640; maximum-scale=1; user-scalable=no">
   	<meta name="robots" content="noindex,nofollow">
    <link rel="apple-touch-icon-precomposed" href="http://genleadership.com/precomp.png">
    <title>Vision Building</title>
    <link rel='stylesheet' id='mapcss'  href='http://genleadership.com/mobileapp/sora/visionbuilding/resources/master.css' type='text/css'>
    <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
    <style type="text/css">
	/* Mobile CSS fixes */
			* {
				-webkit-touch-callout: none;
				-webkit-user-select: none;
			}
	</style>
</head>

<body>
<div id="grand_container">
  <div class="grand_header_roll"><div class="grand_header_roll_userfloat"><a href="#"><?=$username?></a></div></div>
  <div class="grand_spacerheader"></div>
  <!-- End Header -->
